/**
 * generated by Xtext 2.21.0
 */
package smitey.rpgindividual;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entity Move Modifier</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link smitey.rpgindividual.EntityMoveModifier#getMoveName <em>Move Name</em>}</li>
 *   <li>{@link smitey.rpgindividual.EntityMoveModifier#getMoveModification <em>Move Modification</em>}</li>
 * </ul>
 *
 * @see smitey.rpgindividual.RpgindividualPackage#getEntityMoveModifier()
 * @model
 * @generated
 */
public interface EntityMoveModifier extends EObject
{
  /**
   * Returns the value of the '<em><b>Move Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Move Name</em>' reference.
   * @see #setMoveName(Move)
   * @see smitey.rpgindividual.RpgindividualPackage#getEntityMoveModifier_MoveName()
   * @model
   * @generated
   */
  Move getMoveName();

  /**
   * Sets the value of the '{@link smitey.rpgindividual.EntityMoveModifier#getMoveName <em>Move Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Move Name</em>' reference.
   * @see #getMoveName()
   * @generated
   */
  void setMoveName(Move value);

  /**
   * Returns the value of the '<em><b>Move Modification</b></em>' containment reference list.
   * The list contents are of type {@link smitey.rpgindividual.EntityMoveMultiplier}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Move Modification</em>' containment reference list.
   * @see smitey.rpgindividual.RpgindividualPackage#getEntityMoveModifier_MoveModification()
   * @model containment="true"
   * @generated
   */
  EList<EntityMoveMultiplier> getMoveModification();

} // EntityMoveModifier
