/**
 * generated by Xtext 2.21.0
 */
package smitey.rpgindividual;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entity Move Multiplier</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link smitey.rpgindividual.EntityMoveMultiplier#getAttribute <em>Attribute</em>}</li>
 *   <li>{@link smitey.rpgindividual.EntityMoveMultiplier#getMultiplier <em>Multiplier</em>}</li>
 * </ul>
 *
 * @see smitey.rpgindividual.RpgindividualPackage#getEntityMoveMultiplier()
 * @model
 * @generated
 */
public interface EntityMoveMultiplier extends EObject
{
  /**
   * Returns the value of the '<em><b>Attribute</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute</em>' reference.
   * @see #setAttribute(Attribute)
   * @see smitey.rpgindividual.RpgindividualPackage#getEntityMoveMultiplier_Attribute()
   * @model
   * @generated
   */
  Attribute getAttribute();

  /**
   * Sets the value of the '{@link smitey.rpgindividual.EntityMoveMultiplier#getAttribute <em>Attribute</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribute</em>' reference.
   * @see #getAttribute()
   * @generated
   */
  void setAttribute(Attribute value);

  /**
   * Returns the value of the '<em><b>Multiplier</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Multiplier</em>' containment reference.
   * @see #setMultiplier(Sum)
   * @see smitey.rpgindividual.RpgindividualPackage#getEntityMoveMultiplier_Multiplier()
   * @model containment="true"
   * @generated
   */
  Sum getMultiplier();

  /**
   * Sets the value of the '{@link smitey.rpgindividual.EntityMoveMultiplier#getMultiplier <em>Multiplier</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Multiplier</em>' containment reference.
   * @see #getMultiplier()
   * @generated
   */
  void setMultiplier(Sum value);

} // EntityMoveMultiplier
